### ISSUE TITLE
dcm2niix or dicom2nifti

### ISSUE THREAD

**Issue by dazzag24** [softwiredtech/niivue-dcm2niix#1]
Hi,

The README refers to dcm2niix from https://github.com/rordenlab/dcm2niix.  However the actual js files downloaded from the https://github.com/wpmed92/WebMRI/ repo by [fetch_dcm2niix.sh](https://github.com/softwiredtech/niivue-dcm2niix/blob/main/fetch_dcm2niix.sh) seem to be a emscripten port of https://github.com/icometrix/dicom2nifti.

Thanks

**Comment by wpmed92** [comment]
Hi,

Please, have a look at your console output when running the program:

<img width="606" alt="Screenshot 2024-04-19 at 12 14 36" src="https://github.com/softwiredtech/niivue-dcm2niix/assets/8374618/59078628-6884-48d9-90a5-0904a83f7019">

This is just loading some random non-dicom file to see the output. As you can see, it is using dcm2niix. Don't be mislead by the name of the *.js and *.mem files, which are dicom2nifti.

**Comment by dazzag24** [comment]
Hi,

Thanks for the clarification. Do you know where the repo is for the port of
dcm2niix to js / wasm is?

**Comment by wpmed92** [comment]
I'll put up the repo for the actual port, WebMRI repo only holds the already ported files for dcm2niix.
